### ISSUE TITLE
Font Awesome not working

### ISSUE THREAD

**Issue by coder2000** [riboseinc/jekyll-theme-open-project#64]
CDN being used for Font Awesome is for users who have paid for Pro. It should probably be switched to the free version or have a config switch.

**Comment by ronaldtse** [comment]
Thanks @coder2000 !

@strogonoff could you help take care of this? Thanks!

**Comment by strogonoff** [comment]
@ronaldtse 

I am not satisfied in the solution currently in pull request(s), I think it’s too complex.

We have the following situation (feel free to skip to my proposed solution below):

* As theme user, I want to be able to create an open project/hub site with as little effort (configuration) as possible.

* Once I go production, I may want to deviate from defaults in any combination of the following:

The default|Reasons to change|Change how
----|----|----
Include all FA styles|Performance (may be loading unused icons)|Include only specific styles
Free version (upcoming default)|More icons for custom styling|Use Pro version
Include latest FA version at the time of theme release|New or updated icons|Specify FA release
Use official FA CDN|Performance, intranet, China, etc.|Host FA files on my own hosting or another CDN

* (A) As a non-designer who wants the site functional, I don’t really care about customizing icon styles. Or:

* (B) As a designer who wants to achieve a specific appearance, I want control over which icon style is used in which UI widget (one site-wide setting for icon style would not suffice for me—I’ll have to override includes).

I think the best way is to make it zero-configuration by default, and if any customization is needed then the user sets `fontawesome_cdn: no` and specifies custom `<script>` tags inside a template include.

Let me know if there’s something I’m missing, otherwise I’m going to build upon your PRs and change the following in upcoming release:

* Stop using FA Pro icon styles, if any
* Update default FA CDN setup to use free version
* Support one new setting `fontawesome_cdn: no`
* Update default layout, allowing users to extend `<head>` contents via template include

**Comment by ronaldtse** [comment]
Maybe I'm misunderstanding, but right now it is zero configuration and defaults to the free version.

In any case, the suggestions you made are excellent, so please help go ahead with them 👍

**Comment by strogonoff** [comment]
Great! I s zero-configuration as the default is done right in the PRs, only the (optional) configuration method doesn’t feel 100% right.

**Comment by strogonoff** [comment]
We did end up using one icon that is not supported in free in any style (`external-link-square`), but its version is indistinguishable and is available in solid.

Merging Ronald’s branch with following changes:

- Add & document configuration kill-switch `no_auto_fontawesome`
- Add configuration option `fontawesome_cdn` to allow us to update FA version & integrity on new releases with less hassle
- Have icons use `fas` style instead of configurable style (some icons require different whitespace measurements depending on style and my judgement is that the overhead doesn’t justify the ends)
- Add head.html include to allow the user specify custom FA distribution
- Update docs to specify which FA distribution theme expects

**Comment by strogonoff** [comment]
Going to include in 2.0.2 release

**Comment by strogonoff** [comment]
The new triple-dot does doesn’t really work as well, but I’ll leave it for now to bug me to redesign expandable documentation navigation UX.

Before:

<img width="361" alt="Screen Shot 2019-04-07 at 10 52 03 AM" src="https://user-images.githubusercontent.com/292959/55677906-62edf480-5923-11e9-8587-6eb3d28f0904.png">

After:

<img width="338" alt="Screen Shot 2019-04-07 at 10 51 00 AM" src="https://user-images.githubusercontent.com/292959/55677907-697c6c00-5923-11e9-87af-1908992609d7.png">

It escaped my notice that we did in fact use light FA styles before, and they all now became solid

**Comment by strogonoff** [comment]
I’ll reopen this to remind myself to double-check for possible degraded looks after icon style change and adjust measurements if necessary

**Comment by strogonoff** [comment]
Should be all good.
